[package]
name = "darkfi_insurance_market_contract"
version = "0.1.0"
edition = "2021"
authors = ["DarkFi Developers"]
license = "AGPL-3.0"

[lib]
name = "darkfi_insurance_market_contract"
crate-type = ["lib", "cdylib"]

[dependencies]
darkfi-sdk = { path = "../../sdk", features = ["wasm"] }
darkfi-serial = { path = "../../serial", features = ["derive", "crypto"] }
thiserror = "1.0"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }

[features]
default = []
no-entrypoint = []
client = []