[package]
name = "dwow_baccarat_contract"
version = "0.1.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pasta_curves = "0.5.1"
blake3 = "1.8.2"
bs58 = "0.5.1"
dwow-sdk = { path = "../../sdk", features = ["wasm"] }
dwow_entropy_contract = { path = "../entropy" }
dwow-serial = { path = "../../serial", features = ["derive", "crypto"] }
thiserror = "2.0.17"

# The following dependencies are used for the client API and
# probably shouldn't be in WASM
dwow_core = { path = "../../../", features = ["zk"], optional = true }
chacha20poly1305 = { version = "0.10.1", optional = true }
halo2_proofs = { version = "0.3.2", optional = true }
tracing = { version = "0.1.44", optional = true }
rand = { version = "0.8.5", optional = true }

# Misc
lazy_static = "1.5.0"
dwow_promissory_note_contract = { version = "0.1.0", path = "../promissory_note", features = ["no-entrypoint"] }

# These are used just for the integration tests
[dev-dependencies]
smol = "2.0.2"
dwow-contract-test-harness = {path = "../test-harness"}

# We need to disable random using "custom" which makes the crate a noop
# so the wasm32-unknown-unknown target is enabled.
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.8", features = ["custom"] }
dwow-sdk = { path = "../../sdk", features = ["wasm"] }

[features]
default = []
no-entrypoint = []
client = [
    "dwow_core",
    "dwow-serial/async",

    "rand",
    "chacha20poly1305",
    "tracing",
    "halo2_proofs",
]

[lints]
workspace = true
