[package]
name = "dwow-accounts"
version = "0.5.0"
homepage = "https://darkwow.org"
description = "DarkWow Account Manager — unified key management for miners and wallets"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
dwow-sdk = {path = "../../src/sdk"}
rand = "0.8.5"
sled = "0.34"
serde_json = "1.0"
hex = "0.4.3"
toml = "0.9.8"
sha2 = "0.10.9"
hmac = "0.12.1"
pasta_curves = "0.5.1"
bs58 = "0.5.1"
