[package]
name = "dwow-accounts"
version = "0.5.0"
homepage = "https://darkwow.org"
description = "DarkWow Account Manager — unified key management for miners and wallets"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
dwow-sdk = {path = "../../src/sdk"}
hex = "0.4.3"
toml = "0.9.8"
bs58 = "0.5.1"
rand = "0.8.5"
