[package]
name = "dwow-system"
version = "0.5.0"
homepage = "https://darkwow.org"
description = "DarkWow async runtime helpers"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
smol = "2.0.2"
parking_lot = "0.12.5"
libc = "0.2.178"
rand = "0.8.5"
pin-project-lite = "0.2.16"
tracing = "0.1.44"

[dev-dependencies]
futures = "0.3"
