[package]
name = "dwow_escrow_contract"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dwow-sdk = { path = "../../sdk", features = ["wasm"] }
dwow-serial = { path = "../../serial", features = ["derive", "crypto"] }
thiserror = "2.0.17"
serde = "1.0"
sled = "0.34"
tracing = "0.1.44"

# The following dependencies are used for the client API
dwow = { path = "../../../", features = ["zk"], optional = true }
rand = { version = "0.8.5", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.8", features = ["custom"] }
dwow-sdk = { path = "../../sdk", features = ["wasm"] }

[features]
default = []
no-entrypoint = []
client = [
    "dwow",
    "dwow-serial/async",
    "rand",
]

[lints]
workspace = true
