#!/usr/bin/env bash
# Generate real random keys for the DarkWow test pipeline.
#
# Uses `dwow_keygen generate` (via Docker) — the AccountManager lifecycle CLI.
# Produces a fresh 64-char hex secret, persisted to the lifecycle blob. One
# unique key per mining node + observer; wallet-1 SHARES node0's key (so it can
# decrypt node0's coinbase); wallet-2 gets its own key (funded via transfer).
#
# Output: keys.toml in the same directory as this script.
#
# Usage:
#   ./contrib/docker/darkwow-testnet/generate-keys.sh
#
# Requirements:
#   - darkwow-testnet:latest Docker image (built via test_pipeline.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KEYS_FILE="${SCRIPT_DIR}/keys.toml"
IMAGE="darkwow-testnet:latest"

if ! docker image inspect "$IMAGE" &>/dev/null; then
    echo "ERROR: Docker image $IMAGE not found. Build it first via test_pipeline.sh."
    exit 1
fi

if [ -f "$KEYS_FILE" ]; then
    echo "WARNING: $KEYS_FILE already exists."
    grep "wallet_secret" "$KEYS_FILE" | sed 's/\(........\)\(.*\)\(........\)/\1...\3/' || true
    read -rp "Overwrite with new random keys? [y/N] " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Generate one fresh random 64-hex secret via the owner-run generator.
# Key generation is an AccountManager lifecycle operation (dwow_keygen).
genkey() {
    docker run --rm "$IMAGE" /app/dwow_keygen generate 2>/dev/null
}

# Every dwowd node that boots needs a declared key (no auto-generation). Sections:
#   node0..node4, observer — mining/validation nodes
#   wallet-1 = node0       — shares node0's key to decrypt its coinbase
#   wallet-2               — separate, funded via transfer
NODE_SECTIONS=(node0 node1 node2 node3 node4 observer)

declare -A KEYS
for section in "${NODE_SECTIONS[@]}"; do
    echo "Generating key for [$section]..."
    hex="$(genkey)"
    if [ "${#hex}" -ne 64 ]; then
        echo "ERROR: [$section] key is ${#hex} chars (expected 64): $hex"
        exit 1
    fi
    KEYS[$section]="$hex"
    echo "  [$section]: ${hex:0:16}..."
done

echo "Generating key for [wallet-2]..."
WALLET2_HEX="$(genkey)"
if [ "${#WALLET2_HEX}" -ne 64 ]; then
    echo "ERROR: wallet-2 key is ${#WALLET2_HEX} chars (expected 64)"
    exit 1
fi
echo "  [wallet-2]: ${WALLET2_HEX:0:16}..."

# Uniqueness sanity check across all distinct keys (node0..node4, observer, wallet-2).
mapfile -t ALL < <(for s in "${NODE_SECTIONS[@]}"; do echo "${KEYS[$s]}"; done; echo "$WALLET2_HEX")
UNIQ=$(printf '%s\n' "${ALL[@]}" | sort -u | wc -l)
if [ "$UNIQ" -ne "${#ALL[@]}" ]; then
    echo "ERROR: duplicate keys generated — astronomically unlikely; aborting."
    exit 1
fi

# Write keys.toml. wallet-1 SHARES node0's key (the coinbase-decryption sharing).
{
    echo "# DarkWow Testnet — Key Configuration"
    echo "#"
    echo "# Generated by generate-keys.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "# Real random keys via 'dwow_keygen generate' (AccountManager lifecycle)."
    echo "#"
    echo "# Every booting node/wallet declares its key here (no auto-generation)."
    echo "# wallet-1 shares node0's key so it can decrypt node0's coinbase and hold"
    echo "# spendable DRKW; wallet-2 is separate and funded via transfer."
    echo ""
    for section in "${NODE_SECTIONS[@]}"; do
        echo "[$section]"
        echo "wallet_secret = \"${KEYS[$section]}\""
        echo ""
    done
    echo "[wallet-1]"
    echo "wallet_secret = \"${KEYS[node0]}\""
    echo ""
    echo "[wallet-2]"
    echo "wallet_secret = \"${WALLET2_HEX}\""
} > "$KEYS_FILE"

echo ""
echo "Keys written to: $KEYS_FILE"
echo "  [wallet-1] shares [node0]; [wallet-2] separate."
echo "Commit this file to use it in the pipeline (Docker builds clone from origin)."
