/* This file is part of DarkWow
 *
 * Copyright (C) 2020-2026 Dyne.org foundation
 *
 * DarkWow is a tool for people and nations to establish sovereignty
 * according to human rights law. See the UN Declaration on the Rights
 * of Indigenous Peoples and associated documents:
 * https://documents.un.org/doc/undoc/gen/g26/031/70/pdf/g2603170.pdf
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! Escrow contract data structures
//!
//! ## State Machine
//!
//! ```text
//! Created ──[Fund]──> Funded ──[Claim]──> Claimed
//!                   │                │
//!                   │                └──[Refund]──> Refunded
//!                   │
//!                   └──[Cancel]──> Cancelled
//! ```
//!
//! - **Created**: Escrow created but not yet funded
//! - **Funded**: Funds locked in commitment, awaiting release condition
//! - **Claimed**: Seller proved knowledge of seller_secret, funds released
//! - **Refunded**: Buyer proved timeout reached, funds returned
//! - **Cancelled**: Buyer cancelled before funding

use dwow_sdk::{
    crypto::{pasta_prelude::PrimeField, poseidon_hash, MerkleNode, PublicKey},
    error::ContractError,
    pasta::{group::GroupEncoding, pallas},
};
use dwow_serial::{SerialDecodable, SerialEncodable};

/// Escrow unique identifier (hash of escrow data)
#[derive(Debug, Clone, Copy, Eq, PartialEq, SerialEncodable, SerialDecodable)]
pub struct EscrowId(pub pallas::Base);
impl EscrowId {
    pub fn inner(&self) -> pallas::Base { self.0 }
    pub fn to_bytes(&self) -> [u8; 32] { self.0.to_repr() }
    pub fn from_bytes(x: [u8; 32]) -> Option<Self> {
        pallas::Base::from_repr(x).into_option().map(Self)
    }
    pub fn is_zero(&self) -> bool { self.0 == pallas::Base::zero() }
    pub fn zero() -> Self { Self(pallas::Base::zero()) }
}

/// Represents the current state of an escrow
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EscrowState {
    /// Escrow created but not yet funded
    Created = 0,
    /// Funds locked, awaiting release condition
    Funded = 1,
    /// Seller claimed funds
    Claimed = 2,
    /// Buyer refunded after timeout
    Refunded = 3,
    /// Cancelled by buyer before funding
    Cancelled = 4,
}

impl TryFrom<u8> for EscrowState {
    type Error = dwow_sdk::error::ContractError;

    fn try_from(b: u8) -> Result<Self, Self::Error> {
        match b {
            0 => Ok(Self::Created),
            1 => Ok(Self::Funded),
            2 => Ok(Self::Claimed),
            3 => Ok(Self::Refunded),
            4 => Ok(Self::Cancelled),
            _ => Err(dwow_sdk::error::ContractError::InvalidFunction),
        }
    }
}

/// Core escrow data stored on-chain.
///
/// ## Box + Purse Integration (Tier 1 Refactor)
///
/// The escrow uses two genesis O-Cap primitives as **child calls**, not as
/// replacement fields. The existing model stays intact. The integration is
/// at the entrypoint level:
/// - Fund creates a Purse::DepositV1 child call to lock funds
/// - Claim calls Box::TakeV1 to consume the seller's claim capability
/// - Refund calls Box::TakeV1 to consume the buyer's refund capability
///
/// The Purse and Box contracts handle balance tracking, nullifier replay,
/// and ZK proof verification — the escrow contract validates only that
/// the child call targets the correct genesis contract.
#[derive(Debug, Clone)]
pub struct Escrow {
    pub version: u8,
    /// Escrow identifier (commitment)
    pub id: EscrowId,
    /// Buyer's public key
    pub buyer_pubkey: PublicKey,
    /// Seller's public key (derived from seller_secret)
    pub seller_pubkey: PublicKey,
    /// Value locked in escrow
    pub value: u64,
    /// Token ID
    pub token_id: pallas::Base,
    /// Timeout block height for refund
    pub timeout: u64,
    /// Current state
    pub state: EscrowState,
    /// Pedersen commitment for the locked value
    pub value_commit: pallas::Point,
    /// Blinding factor used in commitment
    pub value_blind: pallas::Scalar,
    /// Nullifier for the escrow (prevents double-claim/refund)
    pub spent_nullifier: pallas::Base,
    /// Block height when escrow was created
    pub created_at: u64,
    /// Block height when escrow was funded
    pub funded_at: Option<u64>,
    /// Per-instance seed for deriving capability-scoped keys.
    /// Generated by the buyer at creation, shared with the seller
    /// off-chain so both parties derive the same instance key.
    pub instance_seed: [u8; 32],
}

impl Escrow {
    /// Derive the escrow ID from buyer_pubkey, seller_pubkey, value, token_id, and timeout
    #[allow(dead_code)]
    pub fn derive_id(
        buyer_pubkey: &PublicKey,
        seller_pubkey: &PublicKey,
        value: u64,
        token_id: pallas::Base,
        timeout: u64,
        buyer_secret: pallas::Base,
        seller_secret: pallas::Base,
    ) -> EscrowId {
        let (bx, by) = buyer_pubkey.xy().expect("pk not identity");
        let (sx, sy) = seller_pubkey.xy().expect("pk not identity");
        EscrowId(poseidon_hash([
            bx, by, sx, sy,
            pallas::Base::from(value),
            token_id,
            pallas::Base::from(timeout),
            buyer_secret,
            seller_secret,
        ]))
    }

    /// Compute the nullifier that prevents double-claim or double-refund
    #[allow(dead_code)]
    pub fn compute_nullifier(&self, secret: pallas::Base) -> pallas::Base {
        poseidon_hash([self.id.0, secret])
    }
}

impl Escrow {
    /// Fixed canonical byte size:
    ///   version(1) + id(32) + buyer_pubkey(32) + seller_pubkey(32) +
    ///   value(8) + token_id(32) + timeout(8) + state(1) +
    ///   value_commit(32) + value_blind(32) + spent_nullifier(32) +
    ///   created_at(8) + funded_at(9) + instance_seed(32)
    pub const ENCODED_SIZE: usize = 291;

    /// Encode to canonical bytes (rho-calculus: quote).
    pub fn encode(&self) -> Vec<u8> {
        let mut b = Vec::with_capacity(Self::ENCODED_SIZE);
        b.push(self.version);
        b.extend_from_slice(&self.id.to_bytes());
        b.extend_from_slice(&self.buyer_pubkey.to_bytes());
        b.extend_from_slice(&self.seller_pubkey.to_bytes());
        b.extend_from_slice(&self.value.to_le_bytes());
        b.extend_from_slice(&self.token_id.to_repr());
        b.extend_from_slice(&self.timeout.to_le_bytes());
        b.push(self.state as u8);
        b.extend_from_slice(&self.value_commit.to_bytes());
        b.extend_from_slice(&self.value_blind.to_repr());
        b.extend_from_slice(&self.spent_nullifier.to_repr());
        b.extend_from_slice(&self.created_at.to_le_bytes());
        b.push(self.funded_at.is_some() as u8);
        if let Some(fa) = self.funded_at {
            b.extend_from_slice(&fa.to_le_bytes());
        } else {
            b.extend_from_slice(&[0u8; 8]);
        }
        b.extend_from_slice(&self.instance_seed);
        b
    }

    /// Decode from canonical bytes (rho-calculus: eval).
    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != Self::ENCODED_SIZE {
            return Err(ContractError::IoError(format!(
                "Escrow: expected {} bytes, got {}",
                Self::ENCODED_SIZE, data.len()
            )));
        }
        let version = data[0];
        let id = EscrowId::from_bytes(data[1..33].try_into().unwrap())
            .ok_or_else(|| ContractError::IoError("Escrow: invalid id".into()))?;
        let buyer_pubkey = PublicKey::from_bytes(data[33..65].try_into().unwrap())
            .map_err(|e| ContractError::IoError(format!("Escrow: invalid buyer_pubkey: {}", e)))?;
        let seller_pubkey = PublicKey::from_bytes(data[65..97].try_into().unwrap())
            .map_err(|e| ContractError::IoError(format!("Escrow: invalid seller_pubkey: {}", e)))?;
        let value = u64::from_le_bytes(data[97..105].try_into().unwrap());
        let token_id = Option::<pallas::Base>::from(
            pallas::Base::from_repr(data[105..137].try_into().unwrap())
        ).ok_or_else(|| ContractError::IoError("Escrow: invalid token_id".into()))?;
        let timeout = u64::from_le_bytes(data[137..145].try_into().unwrap());
        let state = EscrowState::try_from(data[145])?;
        let value_commit = Option::<pallas::Point>::from(
            pallas::Point::from_bytes(data[146..178].try_into().unwrap())
        ).ok_or_else(|| ContractError::IoError("Escrow: invalid value_commit".into()))?;
        let value_blind = Option::<pallas::Scalar>::from(
            pallas::Scalar::from_repr(data[178..210].try_into().unwrap())
        ).ok_or_else(|| ContractError::IoError("Escrow: invalid value_blind".into()))?;
        let spent_nullifier = Option::<pallas::Base>::from(
            pallas::Base::from_repr(data[210..242].try_into().unwrap())
        ).ok_or_else(|| ContractError::IoError("Escrow: invalid spent_nullifier".into()))?;
        let created_at = u64::from_le_bytes(data[242..250].try_into().unwrap());
        let funded_at = if data[250] != 0 {
            Some(u64::from_le_bytes(data[251..259].try_into().unwrap()))
        } else {
            None
        };
        let instance_seed: [u8; 32] = data[259..291].try_into().unwrap();
        Ok(Escrow {
            version,
            id,
            buyer_pubkey,
            seller_pubkey,
            value,
            token_id,
            timeout,
            state,
            value_commit,
            value_blind,
            spent_nullifier,
            created_at,
            funded_at,
            instance_seed,
        })
    }
}

/// Parameters for `Escrow::CreateEscrowV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct CreateEscrowParamsV1 {
    /// Buyer's public key
    pub buyer_pubkey: PublicKey,
    /// Seller's public key
    pub seller_pubkey: PublicKey,
    /// Value to be locked in escrow
    pub value: u64,
    /// Token ID
    pub token_id: pallas::Base,
    /// Timeout block height (after which buyer can refund)
    pub timeout: u64,
    /// Commitment to the escrow parameters
    pub commitment: EscrowId,
    /// ZK proof public inputs:
    pub merkle_root: MerkleNode,
    /// Per-instance seed for deriving capability-scoped keys.
    /// Both parties use this seed with derive_instance to produce
    /// distinct pubkeys per escrow instance.
    pub instance_seed: [u8; 32],
}

/// State update for `Escrow::CreateEscrowV1`
#[derive(Debug, Clone)]
pub struct CreateEscrowUpdateV1 {
    /// The created escrow ID
    pub escrow_id: EscrowId,
}

impl CreateEscrowUpdateV1 {
    pub const ENCODED_SIZE: usize = 32;
    pub fn encode(&self) -> Vec<u8> { self.escrow_id.to_bytes().to_vec() }
    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != 32 {
            return Err(ContractError::IoError(format!("CreateEscrowUpdateV1: expected 32 bytes, got {}", data.len())));
        }
        Ok(CreateEscrowUpdateV1 {
            escrow_id: EscrowId::from_bytes(data[0..32].try_into().unwrap())
                .ok_or_else(|| ContractError::IoError("CreateEscrowUpdateV1: invalid escrow_id".into()))?,
        })
    }
}

/// Parameters for `Escrow::FundV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct FundEscrowParamsV1 {
    /// Escrow ID
    pub escrow_id: EscrowId,
    /// Value commitment (Pedersen)
    pub value_commit: pallas::Point,
    /// Merkle proof of the commitment
    pub merkle_proof: Vec<pallas::Base>,
    /// ZK proof public inputs
    pub merkle_root: MerkleNode,
}

/// State update for `Escrow::FundV1`
#[derive(Debug, Clone)]
pub struct FundEscrowUpdateV1 {
    /// The funded escrow ID
    pub escrow_id: EscrowId,
}

impl FundEscrowUpdateV1 {
    pub const ENCODED_SIZE: usize = 32;
    pub fn encode(&self) -> Vec<u8> { self.escrow_id.to_bytes().to_vec() }
    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != 32 {
            return Err(ContractError::IoError(format!("FundEscrowUpdateV1: expected 32 bytes, got {}", data.len())));
        }
        Ok(FundEscrowUpdateV1 {
            escrow_id: EscrowId::from_bytes(data[0..32].try_into().unwrap())
                .ok_or_else(|| ContractError::IoError("FundEscrowUpdateV1: invalid escrow_id".into()))?,
        })
    }
}

/// Parameters for `Escrow::ClaimV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct ClaimEscrowParamsV1 {
    /// Escrow ID
    pub escrow_id: EscrowId,
    /// Seller's secret (proves ownership)
    pub seller_secret: pallas::Base,
    /// Nullifier revealing the escrow is spent
    pub spent_nullifier: pallas::Base,
    /// Recipient public key for the funds
    pub recipient_pubkey: PublicKey,
}

/// State update for `Escrow::ClaimEscrowV1`
#[derive(Debug, Clone)]
pub struct ClaimEscrowUpdateV1 {
    /// The claimed escrow ID
    pub escrow_id: EscrowId,
    /// Nullifier for the spent escrow
    pub spent_nullifier: pallas::Base,
}

impl ClaimEscrowUpdateV1 {
    pub const ENCODED_SIZE: usize = 64;
    pub fn encode(&self) -> Vec<u8> {
        let mut b = Vec::with_capacity(64);
        b.extend_from_slice(&self.escrow_id.to_bytes());
        b.extend_from_slice(&self.spent_nullifier.to_repr());
        b
    }
    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != 64 {
            return Err(ContractError::IoError(format!("ClaimEscrowUpdateV1: expected 64 bytes, got {}", data.len())));
        }
        Ok(ClaimEscrowUpdateV1 {
            escrow_id: EscrowId::from_bytes(data[0..32].try_into().unwrap())
                .ok_or_else(|| ContractError::IoError("ClaimEscrowUpdateV1: invalid escrow_id".into()))?,
            spent_nullifier: Option::<pallas::Base>::from(
                pallas::Base::from_repr(data[32..64].try_into().unwrap())
            ).ok_or_else(|| ContractError::IoError("ClaimEscrowUpdateV1: invalid spent_nullifier".into()))?,
        })
    }
}

/// Parameters for `Escrow::RefundV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct RefundEscrowParamsV1 {
    /// Escrow ID
    pub escrow_id: EscrowId,
    /// Buyer's secret (proves ownership)
    pub buyer_secret: pallas::Base,
    /// Nullifier revealing the escrow is spent
    pub spent_nullifier: pallas::Base,
    /// Current block height (proves timeout reached)
    pub current_block: u64,
    /// Timeout block height (must match escrow timeout for ZK proof)
    pub timeout: u64,
    /// Recipient public key for the refunded funds
    pub recipient_pubkey: PublicKey,
}

/// State update for `Escrow::RefundEscrowV1`
#[derive(Debug, Clone)]
pub struct RefundEscrowUpdateV1 {
    /// The refunded escrow ID
    pub escrow_id: EscrowId,
    /// Nullifier for the spent escrow
    pub spent_nullifier: pallas::Base,
}

impl RefundEscrowUpdateV1 {
    pub const ENCODED_SIZE: usize = 64;
    pub fn encode(&self) -> Vec<u8> {
        let mut b = Vec::with_capacity(64);
        b.extend_from_slice(&self.escrow_id.to_bytes());
        b.extend_from_slice(&self.spent_nullifier.to_repr());
        b
    }
    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != 64 {
            return Err(ContractError::IoError(format!("RefundEscrowUpdateV1: expected 64 bytes, got {}", data.len())));
        }
        Ok(RefundEscrowUpdateV1 {
            escrow_id: EscrowId::from_bytes(data[0..32].try_into().unwrap())
                .ok_or_else(|| ContractError::IoError("RefundEscrowUpdateV1: invalid escrow_id".into()))?,
            spent_nullifier: Option::<pallas::Base>::from(
                pallas::Base::from_repr(data[32..64].try_into().unwrap())
            ).ok_or_else(|| ContractError::IoError("RefundEscrowUpdateV1: invalid spent_nullifier".into()))?,
        })
    }
}

/// Parameters for `Escrow::CancelV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct CancelEscrowParamsV1 {
    /// Escrow ID
    pub escrow_id: EscrowId,
    /// Buyer's public key (must match stored escrow)
    pub buyer_pubkey: PublicKey,
    /// Cancel nullifier = H(escrow_id, buyer_secret) — ZK circuit output
    pub cancel_nullifier: pallas::Base,
}

/// State update for `Escrow::CancelV1`
#[derive(Debug, Clone)]
pub struct CancelEscrowUpdateV1 {
    /// The cancelled escrow ID
    pub escrow_id: EscrowId,
    /// Cancel nullifier — recorded to prevent double-cancel
    pub cancel_nullifier: pallas::Base,
}

impl CancelEscrowUpdateV1 {
    pub const ENCODED_SIZE: usize = 64;
    pub fn encode(&self) -> Vec<u8> {
        let mut b = Vec::with_capacity(64);
        b.extend_from_slice(&self.escrow_id.to_bytes());
        b.extend_from_slice(&self.cancel_nullifier.to_repr());
        b
    }
    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != 64 {
            return Err(ContractError::IoError(format!("CancelEscrowUpdateV1: expected 64 bytes, got {}", data.len())));
        }
        Ok(CancelEscrowUpdateV1 {
            escrow_id: EscrowId::from_bytes(data[0..32].try_into().unwrap())
                .ok_or_else(|| ContractError::IoError("CancelEscrowUpdateV1: invalid escrow_id".into()))?,
            cancel_nullifier: Option::<pallas::Base>::from(
                pallas::Base::from_repr(data[32..64].try_into().unwrap())
            ).ok_or_else(|| ContractError::IoError("CancelEscrowUpdateV1: invalid cancel_nullifier".into()))?,
        })
    }
}
