[package]
name = "dwow_game_room_contract"
version = "0.1.0"
edition = "2021"
authors = ["DarkFi contributors"]
description = "DarkFi Game Room Contract - Generalized betting and pot management"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dwow-sdk = { path = "../../sdk", features = ["wasm"] }
dwow-serial = { path = "../../serial" }

dwow_core = { path = "../../../", features = ["zk"], optional = true }
chacha20poly1305 = { version = "0.10.1", optional = true }
halo2_proofs = { version = "0.3.2", optional = true }
tracing = { version = "0.1.44", optional = true }
rand = { version = "0.8.5", optional = true }
dwow_money_v3_contract = { version = "0.1.0", path = "../money_v3", features = ["no-entrypoint"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[features]
default = []
no-entrypoint = []
client = [
    "dwow_core",
    "dwow-serial/async",
    "rand",
    "chacha20poly1305",
    "tracing",
    "halo2_proofs",
]

[dev-dependencies]
serial_test = "3"

[lints]
workspace = true
