[package]
name = "dwow_money_v3_contract"
version = "0.1.0"
edition = "2021"
authors = ["DarkFi contributors"]
description = "DarkFi Money V3 Contract - Privacy-first, no EC operations"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dwow-sdk = { path = "../../sdk", features = ["wasm"] }
dwow-serial = { path = "../../serial", features = ["derive", "crypto"] }
pasta_curves = "0.5.1"
thiserror = "2.0.17"

# The following dependencies are used for the client API and
# probably shouldn't be in WASM
dwow = { path = "../../../", features = ["zk"], optional = true }
chacha20poly1305 = { version = "0.10.1", optional = true }
halo2_proofs = { version = "0.3.2", optional = true }
tracing = { version = "0.1.44", optional = true }
rand = { version = "0.8.5", optional = true }

[features]
default = []
no-entrypoint = []
client = [
    "dwow",
    "dwow-serial/async",
    "rand",
    "chacha20poly1305",
    "tracing",
    "halo2_proofs",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.8", features = ["custom"] }
dwow-sdk = { path = "../../sdk", features = ["wasm"] }

[lints]
workspace = true

# These are used just for the integration tests
[dev-dependencies]
smol = "2.0.2"
rand = "0.8.5"