[package]
name = "dwow_tender_contract"
version = "0.1.0"
edition = "2021"
authors = ["DarkFi contributors"]
description = "DarkFi Tender Contract - O-Cap tendering system with proposals"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake3 = "1.8.2"
dwow-sdk = { path = "../../sdk", features = ["wasm"] }
dwow-serial = { path = "../../serial", features = ["derive", "crypto"] }
thiserror = "2.0.17"

dwow_core = { path = "../../../", features = ["zk"], optional = true }
chacha20poly1305 = { version = "0.10.1", optional = true }
halo2_proofs = { version = "0.3.2", optional = true }
tracing = { version = "0.1.44", optional = true }
rand = { version = "0.8.5", optional = true }

lazy_static = "1.5.0"

[dev-dependencies]
smol = "2.0.2"
dwow-contract-test-harness = {path = "../test-harness"}

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.8", features = ["custom"] }
dwow-sdk = { path = "../../sdk", features = ["wasm"] }

[features]
default = []
no-entrypoint = []
client = [
    "dwow_core",
    "dwow-serial/async",
    "rand",
    "chacha20poly1305",
    "tracing",
    "halo2_proofs",
]

[lints]
workspace = true