[package]
name = "dwow_linear"
version = "0.1.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"

[features]
default = []
async = ["dwow-serial/async"]

[dependencies]
sled = "0.34"
thiserror = "1"
tracing = "0.1"
blake3 = { version = "1", features = ["serde"] }
rand = "0.8"
randomx = { git = "https://codeberg.org/darkrenaissance/RandomX", rev = "0e31d5a" }
sha2 = "0.10"
merlin = "3"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
ed25519-dalek = "2"
ureq = "3"
monero = { version = "0.21.0" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
primitive-types = { version = "0.14.0" }
dwow-sdk = { path = "../sdk", features = ["async"] }
dwow-serial = { path = "../serial", features = ["derive", "async"] }

[dev-dependencies]
smol = "2"