[package]
name = "darkfi_linear"
version = "0.1.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"

[features]
default = []
async = ["darkfi-serial/async"]

[dependencies]
sled = "0.34"
thiserror = "1"
tracing = "0.1"
blake3 = { version = "1", features = ["serde"] }
rand = "0.8"
randomx = { git = "https://codeberg.org/darkrenaissance/RandomX", rev = "0e31d5a" }
sha2 = "0.10"
merlin = "3"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
darkfi-serial = { path = "../serial", features = ["derive", "async"] }

[dev-dependencies]