network = "linear-testnet"

[network_config."linear-testnet"]
cache_path = "~/.local/share/darkfi/drk/linear-testnet/wallet1/cache"
wallet_path = "~/.local/share/darkfi/drk/linear-testnet/wallet1/wallet.db"
wallet_pass = "testpassword123"
endpoint = "tcp://node1:28346"
history_path = "~/.local/share/darkfi/drk/linear-testnet/wallet1/history.txt"