import Lake
open Lake DSL

package darkfi_gadgets where
  srcDir := "src"

-- Mathlib: the Field.lean proofs (cross_mul_lt, wraparound_safe, etc.) use
-- Mathlib lemmas (mul_comm, Int.div_lt_iff_lt_mul, pow_le_pow_right). Pinned
-- to the Lean 4.12.0-compatible tag (matches lean-toolchain).
require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "v4.12.0"

-- The DarkFi capability type system and ZK gadget specifications.
-- See doc/src/arch/type-system.md for the formal specification this
-- formalizes. Cryptographic properties (collision resistance, binding,
-- zero-knowledge) are assumed as axioms — these correspond to the
-- same assumptions the ZK circuits make. The theorems proven here
-- verify that the type system, gadget algebra, and supply chain
-- invariants hold GIVEN those cryptographic assumptions.

lean_lib DarkFi where
  roots := #[`DarkFi]

-- The circuit transcription is a library of its own, and deliberately outside the `DarkFi` module
-- subtree so that `lake build DarkFi` does not build it. It is 181 `decide` proofs over 2747
-- statements — the tree's most expensive elaboration by an order of magnitude — and while it sat in
-- `DarkFi`'s glob, a 4-threaded build of that library exhausted this host's memory and froze it
-- (2026-09-24). Both libraries share the package `srcDir`, so this is a partition by glob rather
-- than a second source tree, and `src/` is still scanned by `script/check_lean_axioms.py`, so the
-- move costs this module no coverage. See `scripts/lean-build.sh`.
lean_lib Transcribed where
  roots := #[`Transcribed]

-- The `(r, s) -> circuit` index is a library of its own for the same reason, and one more: it imports
-- `Transcribed`, so a copy under `DarkFi/Circuits/` would pull the transcription's elaboration back
-- onto every `lake build DarkFi` through the import graph — the exact cost the partition above exists
-- to avoid. It is generated by `scripts/gen_circuit_index.py` and freshness-gated like its neighbour,
-- and its 12 theorems close `DisclosureRule` at each pair the capability layer instantiates.
lean_lib CircuitIndex where
  roots := #[`CircuitIndex]

-- The IO simulation suite (`src/Main.lean`): the opcode counterexample scans, the barb-set printouts
-- and the HAZOP/EC classification summaries. It is an `lean_exe` so that the build covers it and
-- `lake exe Main` runs it. **Until 2026-09-24 it was in no `lean_lib` and no `lean_exe`**, so `lake
-- build` never touched it, no gate invoked it, and its 21 compile errors survived in the tree for as
-- long as they did — the file itself said "It does not compile, and has not for some time". Every
-- check it performs now fails the run rather than printing a number beside it, which is what makes
-- wiring it into `scripts/run-all-tests.sh` worth anything.
lean_exe Main where
  root := `Main