[package]
name = "darkfi-contract-test-harness"
version = "0.5.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
darkfi = {path = "../../../", features = ["validator"]}
darkfi-sdk = {path = "../../sdk"}
darkfi-serial = {path = "../../serial", features = ["crypto"]}

darkfi_dao_contract = {path = "../dao", features = ["client", "no-entrypoint"]}
darkfi_dao_escrow_contract = {path = "../dao_escrow", features = ["no-entrypoint"]}
darkfi_dex_contract = {path = "../dex", features = ["no-entrypoint"]}
darkfi-identity-contract = {path = "../identity", features = ["no-entrypoint"]}
darkfi_money_contract = {path = "../money", features = ["client", "no-entrypoint"]}
darkfi_deployooor_contract = {path = "../deployooor", features = ["client", "no-entrypoint"]}
darkfi_stablecoin_contract = {path = "../stablecoin", features = ["client", "no-entrypoint"]}
darkfi_lottery_contract = {path = "../lottery", features = ["no-entrypoint"]}
darkfi_slot_contract = {path = "../slot", features = ["no-entrypoint"]}
darkfi_baccarat_contract = {path = "../baccarat", features = ["no-entrypoint"]}
darkfi_darktoshi_dice_contract = {path = "../darktoshi_dice", features = ["no-entrypoint"]}
darkfi_roulette_contract = {path = "../roulette", features = ["no-entrypoint"]}
darkfi_game_room_contract = { path = "../game_room", package = "game_room_contract" }

num-bigint = "0.4.6"
blake3 = "1.8.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["fmt"] }
rand = "0.8.5"
sled-overlay = "0.1.20"

[lints]
workspace = true
