[package]
name = "dwow-contract-test-harness"
version = "0.5.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dwow = {path = "../../../", features = ["zk"]}
dwow-sdk = {path = "../../sdk"}
dwow-serial = {path = "../../serial", features = ["crypto"]}
dwow_native_token_contract = {path = "../native_token", features = ["client", "no-entrypoint"]}
dwow_money_v3_contract = {path = "../money_v3", features = ["client", "no-entrypoint"]}
dwow_deployooor_contract = {path = "../deployooor", features = ["client", "no-entrypoint"]}
dwow_dex_contract = {path = "../dex", features = ["client", "no-entrypoint"]}
dwow_atomic_swap_contract = {path = "../atomic_swap", features = ["client", "no-entrypoint"]}
dwow_oracle_contract = {path = "../oracle", features = ["client", "no-entrypoint"]}
dwow_stablecoin_contract = {path = "../stablecoin", features = ["client", "no-entrypoint"]}
dwow_auction_contract = {path = "../auction", features = ["client", "no-entrypoint"]}
dwow_subscription_contract = {path = "../subscription", features = ["client", "no-entrypoint"]}
dwow_tender_contract = {path = "../tender", features = ["client", "no-entrypoint"]}
dwow_bridge_contract = {path = "../bridge", features = ["client", "no-entrypoint"]}
dwow_attestation_contract = {path = "../attestation", features = ["client", "no-entrypoint"]}
dwow_identity_contract = {path = "../identity", features = ["client", "no-entrypoint"]}
dwow_escrow_contract = {path = "../escrow", features = ["client", "no-entrypoint"]}
dwow_labor_market_contract = {path = "../labor_market", features = ["client", "no-entrypoint"]}
dwow_dao_escrow_contract = {path = "../dao_escrow", features = ["client", "no-entrypoint"]}
dwow_darkbet_exchange_contract = {path = "../darkbet_exchange", features = ["client", "no-entrypoint"]}
dwow_baccarat_contract = {path = "../baccarat", features = ["client", "no-entrypoint"]}
dwow_pool_stake_contract = {path = "../pool_stake", features = ["client", "no-entrypoint"]}
dwow_roulette_contract = {path = "../roulette", features = ["client", "no-entrypoint"]}
dwow_darktoshi_dice_contract = {path = "../darktoshi_dice", features = ["client", "no-entrypoint"]}
dwow_slot_contract = {path = "../slot", features = ["client", "no-entrypoint"]}
dwow_betting_stake_contract = {path = "../betting_stake", features = ["client", "no-entrypoint"]}
dwow_relayer_endowment_contract = {path = "../relayer_endowment", features = ["client", "no-entrypoint"]}
dwow_lottery_contract = {path = "../lottery", features = ["client", "no-entrypoint"]}
dwow_drain_protection_contract = {path = "../drain_protection", features = ["client", "no-entrypoint"]}
dwow_insurance_market_contract = {path = "../insurance_market", features = ["client", "no-entrypoint"]}
dwow_game_room_contract = {path = "../game_room", features = ["client", "no-entrypoint"]}

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["fmt"] }
rand = "0.8.5"

[[bin]]
name = "test_native_token"
path = "src/native_token.rs"

[[bin]]
name = "test_deployooor"
path = "src/deployooor.rs"

[[bin]]
name = "prove_dao_escrow"
path = "src/prove_dao_escrow.rs"

[[bin]]
name = "prove_stablecoin"
path = "src/prove_stablecoin.rs"

[[bin]]
name = "prove_dex"
path = "src/prove_dex.rs"

[lints]
workspace = true