/* This file is part of DarkWow
 *
 * Copyright (C) 2020-2026 Dyne.org foundation
 *
 * DarkWow is a tool for people and nations to establish sovereignty
 * according to human rights law. See the UN Declaration on the Rights
 * of Indigenous Peoples and associated documents:
 * https://documents.un.org/doc/undoc/gen/g26/031/70/pdf/g2603170.pdf
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! OTC Swap contract data structures
//!
//! ## State Machine
//!
//! ```text
//! Created ──[Fund]──> Funded ──[Execute]──> Executed
//!    │                    │
//!    └──[Cancel]          └──[Cancel]──> Cancelled (timeout only)
//! ```
//!
//! - **Created**: Alice proposed the swap (parameters committed on-chain)
//! - **Funded**: Alice locked her coins via child transfer to promissory_note
//! - **Executed**: Bob completed the swap — both parties' coins exchanged
//! - **Cancelled**: Alice cancelled (Created) or timeout expired (Funded)

use dwow_sdk::{
    crypto::{poseidon_hash, MerkleNode, PublicKey},
    pasta::pallas,
};
use dwow_serial::{SerialDecodable, SerialEncodable};

/// OTC Swap unique identifier (hash of swap data)
pub type SwapId = pallas::Base;

/// Represents the current state of a swap
#[derive(Debug, Clone, Copy, PartialEq, Eq, SerialEncodable, SerialDecodable)]
pub enum SwapState {
    /// Swap created but not yet funded by Alice
    Created = 0,
    /// Alice locked her coins
    Funded = 1,
    /// Swap executed - both parties' coins exchanged
    Executed = 2,
    /// Swap cancelled (by Alice before fund, or after timeout)
    Cancelled = 3,
}

impl TryFrom<u8> for SwapState {
    type Error = dwow_sdk::error::ContractError;

    fn try_from(b: u8) -> Result<Self, Self::Error> {
        match b {
            0 => Ok(Self::Created),
            1 => Ok(Self::Funded),
            2 => Ok(Self::Executed),
            3 => Ok(Self::Cancelled),
            _ => Err(dwow_sdk::error::ContractError::InvalidFunction),
        }
    }
}

/// Core OTC swap data stored on-chain
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct OtcSwap {
    pub version: u8,
    /// Swap identifier (commitment hash)
    pub id: SwapId,
    /// Alice's public key (swap creator)
    pub alice_pubkey: PublicKey,
    /// Bob's public key (counterparty)
    pub bob_pubkey: PublicKey,
    /// Value Alice sends
    pub send_value: u64,
    /// Token ID Alice sends
    pub send_token_id: pallas::Base,
    /// Value Alice wants to receive
    pub recv_value: u64,
    /// Token ID Alice wants to receive
    pub recv_token_id: pallas::Base,
    /// Timeout block height for refund
    pub timeout: u64,
    /// Current state
    pub state: SwapState,
    /// Pedersen commitment for Alice's locked value
    pub alice_value_commit: pallas::Point,
    /// Blinding factor for Alice's commitment
    pub alice_value_blind: pallas::Scalar,
    /// Pedersen commitment for Bob's locked value
    pub bob_value_commit: pallas::Point,
    /// Nullifier for the swap (prevents double-execute/cancel)
    pub spent_nullifier: pallas::Base,
    /// Block height when swap was created
    pub created_at: u64,
    /// Block height when swap was funded
    pub funded_at: Option<u64>,
    /// Per-instance seed for deriving capability-scoped keys.
    /// Generated by Alice at creation, shared with Bob off-chain.
    pub instance_seed: [u8; 32],
}

impl OtcSwap {
    /// Derive the swap ID from swap parameters
    #[allow(dead_code)]
    pub fn derive_id(
        alice_pubkey: &PublicKey,
        bob_pubkey: &PublicKey,
        send_value: u64,
        send_token_id: pallas::Base,
        recv_value: u64,
        recv_token_id: pallas::Base,
        timeout: u64,
        alice_secret: pallas::Base,
    ) -> SwapId {
        let (ax, ay) = alice_pubkey.xy();
        let (bx, by) = bob_pubkey.xy();
        poseidon_hash([
            ax,
            ay,
            bx,
            by,
            pallas::Base::from(send_value),
            send_token_id,
            pallas::Base::from(recv_value),
            recv_token_id,
            pallas::Base::from(timeout),
            alice_secret,
        ])
    }

    /// Compute the nullifier that prevents double-execute or double-cancel
    #[allow(dead_code)]
    pub fn compute_nullifier(&self, secret: pallas::Base) -> pallas::Base {
        poseidon_hash([self.id, secret])
    }
}

/// Parameters for `OtcSwap::CreateSwapV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct CreateSwapParamsV1 {
    /// Alice's public key (swap creator)
    pub alice_pubkey: PublicKey,
    /// Bob's public key (counterparty)
    pub bob_pubkey: PublicKey,
    /// Value Alice sends
    pub send_value: u64,
    /// Token ID Alice sends
    pub send_token_id: pallas::Base,
    /// Value Alice wants to receive
    pub recv_value: u64,
    /// Token ID Alice wants to receive
    pub recv_token_id: pallas::Base,
    /// Timeout block height
    pub timeout: u64,
    /// Commitment to the swap parameters
    pub commitment: SwapId,
    /// Per-instance seed for deriving capability-scoped keys
    pub instance_seed: [u8; 32],
}

/// State update for `OtcSwap::CreateSwapV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct CreateSwapUpdateV1 {
    /// The created swap ID
    pub swap_id: SwapId,
}

/// Parameters for `OtcSwap::FundSwapV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct FundSwapParamsV1 {
    /// Swap ID
    pub swap_id: SwapId,
    /// Value commitment (Pedersen)
    pub value_commit: pallas::Point,
    /// Merkle proof of the commitment
    pub merkle_proof: Vec<pallas::Base>,
    /// ZK proof public inputs
    pub merkle_root: MerkleNode,
}

/// State update for `OtcSwap::FundSwapV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct FundSwapUpdateV1 {
    /// The funded swap ID
    pub swap_id: SwapId,
}

/// Parameters for `OtcSwap::ExecuteSwapV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct ExecuteSwapParamsV1 {
    /// Swap ID
    pub swap_id: SwapId,
    /// Bob's secret (proves he's the counterparty)
    pub bob_secret: pallas::Base,
    /// Nullifier revealing the swap is executed
    pub spent_nullifier: pallas::Base,
    /// Alice's recipient pubkey (for Bob's coins to Alice)
    pub alice_recipient: PublicKey,
    /// Bob's recipient pubkey (for Alice's coins to Bob)
    pub bob_recipient: PublicKey,
}

/// State update for `OtcSwap::ExecuteSwapV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct ExecuteSwapUpdateV1 {
    /// The executed swap ID
    pub swap_id: SwapId,
    /// Nullifier for the executed swap
    pub spent_nullifier: pallas::Base,
}

/// Parameters for `OtcSwap::CancelSwapV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct CancelSwapParamsV1 {
    /// Swap ID
    pub swap_id: SwapId,
    /// Alice's secret (must match creator)
    pub alice_secret: pallas::Base,
    /// Nullifier revealing the swap is cancelled
    pub spent_nullifier: pallas::Base,
    /// Current block height (for timeout verification on Funded state)
    pub current_block: u64,
    /// Timeout block height
    pub timeout: u64,
    /// Recipient public key for refund
    pub recipient_pubkey: PublicKey,
}

/// State update for `OtcSwap::CancelSwapV1`
#[derive(Debug, Clone, SerialEncodable, SerialDecodable)]
pub struct CancelSwapUpdateV1 {
    /// The cancelled swap ID
    pub swap_id: SwapId,
    /// Nullifier for the cancelled swap
    pub spent_nullifier: pallas::Base,
}
