/* This file is part of DarkWow
 *
 * Copyright (C) 2020-2026 Dyne.org foundation
 *
 * DarkWow is a tool for people and nations to establish sovereignty
 * according to human rights law. See the UN Declaration on the Rights
 * of Indigenous Peoples and associated documents:
 * https://documents.un.org/doc/undoc/gen/g26/031/70/pdf/g2603170.pdf
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! OTC Swap contract data structures
//!
//! ## State Machine
//!
//! ```text
//! Created ──[Fund]──> Funded ──[Execute]──> Executed
//!    │                    │
//!    └──[Cancel]          └──[Cancel]──> Cancelled (timeout only)
//! ```
//!
//! - **Created**: Alice proposed the swap (parameters committed on-chain)
//! - **Funded**: Alice locked her coins via child transfer to promissory_note
//! - **Executed**: Bob completed the swap — both parties' coins exchanged
//! - **Cancelled**: Alice cancelled (Created) or timeout expired (Funded)

use dwow_sdk::{
    crypto::{pasta_prelude::PrimeField, poseidon_hash, MerkleNode, PublicKey},
    error::ContractError,
    pasta::{group::GroupEncoding, pallas},
};

/// OTC Swap unique identifier (hash of swap data)
pub type SwapId = pallas::Base;

/// Represents the current state of a swap
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SwapState {
    /// Swap created but not yet funded by Alice
    Created = 0,
    /// Alice locked her coins
    Funded = 1,
    /// Swap executed - both parties' coins exchanged
    Executed = 2,
    /// Swap cancelled (by Alice before fund, or after timeout)
    Cancelled = 3,
}

impl TryFrom<u8> for SwapState {
    type Error = dwow_sdk::error::ContractError;

    fn try_from(b: u8) -> Result<Self, Self::Error> {
        match b {
            0 => Ok(Self::Created),
            1 => Ok(Self::Funded),
            2 => Ok(Self::Executed),
            3 => Ok(Self::Cancelled),
            _ => Err(dwow_sdk::error::ContractError::InvalidFunction),
        }
    }
}

/// Core OTC swap data stored on-chain
#[derive(Debug, Clone)]
pub struct OtcSwap {
    pub version: u8,
    /// Swap identifier (commitment hash)
    pub id: SwapId,
    /// Alice's public key (swap creator)
    pub alice_pubkey: PublicKey,
    /// Bob's public key (counterparty)
    pub bob_pubkey: PublicKey,
    /// Value Alice sends
    pub send_value: u64,
    /// Token ID Alice sends
    pub send_token_id: pallas::Base,
    /// Value Alice wants to receive
    pub recv_value: u64,
    /// Token ID Alice wants to receive
    pub recv_token_id: pallas::Base,
    /// Timeout block height for refund
    pub timeout: u64,
    /// Current state
    pub state: SwapState,
    /// Pedersen commitment for Alice's locked value
    pub alice_value_commit: pallas::Point,
    /// Blinding factor for Alice's commitment
    pub alice_value_blind: pallas::Scalar,
    /// Pedersen commitment for Bob's locked value
    pub bob_value_commit: pallas::Point,
    /// Nullifier for the swap (prevents double-execute/cancel)
    pub spent_nullifier: pallas::Base,
    /// Block height when swap was created
    pub created_at: u64,
    /// Block height when swap was funded
    pub funded_at: Option<u64>,
    /// Per-instance seed for deriving capability-scoped keys.
    /// Generated by Alice at creation, shared with Bob off-chain.
    pub instance_seed: [u8; 32],
}

impl OtcSwap {
    /// Derive the swap ID from swap parameters
    #[allow(dead_code)]
    pub fn derive_id(
        alice_pubkey: &PublicKey,
        bob_pubkey: &PublicKey,
        send_value: u64,
        send_token_id: pallas::Base,
        recv_value: u64,
        recv_token_id: pallas::Base,
        timeout: u64,
        alice_secret: pallas::Base,
    ) -> SwapId {
        let (ax, ay) = alice_pubkey.xy().expect("pk not identity");
        let (bx, by) = bob_pubkey.xy().expect("pk not identity");
        poseidon_hash([
            pallas::Base::from(4),
            ax,
            ay,
            bx,
            by,
            pallas::Base::from(send_value),
            send_token_id,
            pallas::Base::from(recv_value),
            recv_token_id,
            pallas::Base::from(timeout),
            alice_secret,
        ])
    }

    /// Compute the nullifier that prevents double-execute or double-cancel
    #[allow(dead_code)]
    pub fn compute_nullifier(&self, secret: pallas::Base) -> pallas::Base {
        poseidon_hash([pallas::Base::from(1), self.id, secret])
    }
}

impl OtcSwap {
    pub const ENCODED_SIZE: usize = 363;

    pub fn encode(&self) -> Vec<u8> {
        let mut b = Vec::with_capacity(Self::ENCODED_SIZE);
        b.push(self.version);
        b.extend_from_slice(&self.id.to_repr());
        b.extend_from_slice(&self.alice_pubkey.to_bytes());
        b.extend_from_slice(&self.bob_pubkey.to_bytes());
        b.extend_from_slice(&self.send_value.to_le_bytes());
        b.extend_from_slice(&self.send_token_id.to_repr());
        b.extend_from_slice(&self.recv_value.to_le_bytes());
        b.extend_from_slice(&self.recv_token_id.to_repr());
        b.extend_from_slice(&self.timeout.to_le_bytes());
        b.push(self.state as u8);
        b.extend_from_slice(&self.alice_value_commit.to_bytes());
        b.extend_from_slice(&self.alice_value_blind.to_repr());
        b.extend_from_slice(&self.bob_value_commit.to_bytes());
        b.extend_from_slice(&self.spent_nullifier.to_repr());
        b.extend_from_slice(&self.created_at.to_le_bytes());
        b.push(self.funded_at.is_some() as u8);
        if let Some(fa) = self.funded_at {
            b.extend_from_slice(&fa.to_le_bytes());
        } else {
            b.extend_from_slice(&0u64.to_le_bytes());
        }
        b.extend_from_slice(&self.instance_seed);
        b
    }

    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != Self::ENCODED_SIZE {
            return Err(ContractError::IoError(format!(
                "OtcSwap: expected {} bytes, got {}",
                Self::ENCODED_SIZE,
                data.len()
            )));
        }
        let version = data[0];
        let id = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[1..33].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("OtcSwap: invalid id".into()))?;
        let alice_pubkey = PublicKey::from_bytes(data[33..65].try_into().unwrap())
            .map_err(|e| ContractError::IoError(format!("OtcSwap: invalid alice_pubkey: {}", e)))?;
        let bob_pubkey = PublicKey::from_bytes(data[65..97].try_into().unwrap())
            .map_err(|e| ContractError::IoError(format!("OtcSwap: invalid bob_pubkey: {}", e)))?;
        let send_value = u64::from_le_bytes(data[97..105].try_into().unwrap());
        let send_token_id = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[105..137].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("OtcSwap: invalid send_token_id".into()))?;
        let recv_value = u64::from_le_bytes(data[137..145].try_into().unwrap());
        let recv_token_id = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[145..177].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("OtcSwap: invalid recv_token_id".into()))?;
        let timeout = u64::from_le_bytes(data[177..185].try_into().unwrap());
        let state = SwapState::try_from(data[185])?;
        let alice_value_commit = Option::<pallas::Point>::from(pallas::Point::from_bytes(
            data[186..218].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("OtcSwap: invalid alice_value_commit".into()))?;
        let alice_value_blind = Option::<pallas::Scalar>::from(pallas::Scalar::from_repr(
            data[218..250].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("OtcSwap: invalid alice_value_blind".into()))?;
        let bob_value_commit = Option::<pallas::Point>::from(pallas::Point::from_bytes(
            data[250..282].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("OtcSwap: invalid bob_value_commit".into()))?;
        let spent_nullifier = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[282..314].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("OtcSwap: invalid spent_nullifier".into()))?;
        let created_at = u64::from_le_bytes(data[314..322].try_into().unwrap());
        let funded_at = if data[322] != 0 {
            Some(u64::from_le_bytes(data[323..331].try_into().unwrap()))
        } else {
            None
        };
        let instance_seed: [u8; 32] = data[331..363].try_into().unwrap();
        Ok(OtcSwap {
            version,
            id,
            alice_pubkey,
            bob_pubkey,
            send_value,
            send_token_id,
            recv_value,
            recv_token_id,
            timeout,
            state,
            alice_value_commit,
            alice_value_blind,
            bob_value_commit,
            spent_nullifier,
            created_at,
            funded_at,
            instance_seed,
        })
    }
}

fn read_base(data: &[u8]) -> Result<pallas::Base, ContractError> { Option::<pallas::Base>::from(pallas::Base::from_repr(data.try_into().unwrap())).ok_or_else(|| ContractError::IoError("invalid base".into())) }

/// Parameters for `OtcSwap::CreateSwapV1`
#[derive(Debug, Clone,)]
pub struct CreateSwapParamsV1 {
    /// Alice's public key (swap creator)
    pub alice_pubkey: PublicKey,
    /// Bob's public key (counterparty)
    pub bob_pubkey: PublicKey,
    /// Value Alice sends
    pub send_value: u64,
    /// Token ID Alice sends
    pub send_token_id: pallas::Base,
    /// Value Alice wants to receive
    pub recv_value: u64,
    /// Token ID Alice wants to receive
    pub recv_token_id: pallas::Base,
    /// Timeout block height
    pub timeout: u64,
    /// Commitment to the swap parameters
    pub commitment: SwapId,
    /// Per-instance seed for deriving capability-scoped keys
    pub instance_seed: [u8; 32],
}

impl dwow_serial::Encodable for CreateSwapParamsV1 { fn encode<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<usize> { let b = self.encode(); w.write_all(&b)?; Ok(b.len()) } }
impl dwow_serial::Decodable for CreateSwapParamsV1 { fn decode<D: std::io::Read>(d: &mut D) -> std::io::Result<Self> { let mut b = vec![]; d.read_to_end(&mut b)?; Self::decode(&b).map_err(|e| std::io::Error::other(format!("{e}"))) } }
impl CreateSwapParamsV1 {
    pub const ENCODED_SIZE: usize = 216;
    pub fn encode(&self) -> Vec<u8> {
        let mut buf = Vec::with_capacity(Self::ENCODED_SIZE);
        buf.extend_from_slice(&self.alice_pubkey.to_bytes()); buf.extend_from_slice(&self.bob_pubkey.to_bytes());
        buf.extend_from_slice(&self.send_value.to_le_bytes()); buf.extend_from_slice(&self.send_token_id.to_repr());
        buf.extend_from_slice(&self.recv_value.to_le_bytes()); buf.extend_from_slice(&self.recv_token_id.to_repr());
        buf.extend_from_slice(&self.timeout.to_le_bytes()); buf.extend_from_slice(&self.commitment.to_repr());
        buf.extend_from_slice(&self.instance_seed); buf
    }
    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != Self::ENCODED_SIZE { return Err(ContractError::IoError(format!("CreateSwapParamsV1: expected {} bytes, got {}", Self::ENCODED_SIZE, data.len()))); }
        let alice_pubkey = PublicKey::from_bytes(data[0..32].try_into().unwrap()).map_err(|e| ContractError::IoError(format!("CreateSwapParamsV1: invalid alice_pubkey: {}", e)))?;
        let bob_pubkey = PublicKey::from_bytes(data[32..64].try_into().unwrap()).map_err(|e| ContractError::IoError(format!("CreateSwapParamsV1: invalid bob_pubkey: {}", e)))?;
        let send_value = u64::from_le_bytes(data[64..72].try_into().unwrap());
        let send_token_id = read_base(&data[72..104])?;
        let recv_value = u64::from_le_bytes(data[104..112].try_into().unwrap());
        let recv_token_id = read_base(&data[112..144])?;
        let timeout = u64::from_le_bytes(data[144..152].try_into().unwrap());
        let commitment = read_base(&data[152..184])?;
        let instance_seed: [u8; 32] = data[184..216].try_into().unwrap();
        Ok(CreateSwapParamsV1 { alice_pubkey, bob_pubkey, send_value, send_token_id, recv_value, recv_token_id, timeout, commitment, instance_seed })
    }
}

/// State update for `OtcSwap::CreateSwapV1`
#[derive(Debug, Clone)]
pub struct CreateSwapUpdateV1 {
    /// The created swap ID
    pub swap_id: SwapId,
}

impl dwow_serial::Encodable for CreateSwapUpdateV1 { fn encode<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<usize> { let b = self.encode(); w.write_all(&b)?; Ok(b.len()) } }
impl dwow_serial::Decodable for CreateSwapUpdateV1 { fn decode<D: std::io::Read>(d: &mut D) -> std::io::Result<Self> { let mut b = vec![]; d.read_to_end(&mut b)?; Self::decode(&b).map_err(|e| std::io::Error::other(format!("{e}"))) } }
impl CreateSwapUpdateV1 {
    pub const ENCODED_SIZE: usize = 32;

    pub fn encode(&self) -> Vec<u8> {
        self.swap_id.to_repr().to_vec()
    }

    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != Self::ENCODED_SIZE {
            return Err(ContractError::IoError(format!(
                "CreateSwapUpdateV1: expected {} bytes, got {}",
                Self::ENCODED_SIZE,
                data.len()
            )));
        }
        let swap_id = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[0..32].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("CreateSwapUpdateV1: invalid swap_id".into()))?;
        Ok(CreateSwapUpdateV1 { swap_id })
    }
}

/// Parameters for `OtcSwap::FundSwapV1`
#[derive(Debug, Clone,)]
pub struct FundSwapParamsV1 {
    /// Swap ID
    pub swap_id: SwapId,
    /// Value commitment (Pedersen)
    pub value_commit: pallas::Point,
    /// Merkle proof of the commitment
    pub merkle_proof: Vec<pallas::Base>,
    /// ZK proof public inputs
    pub merkle_root: MerkleNode,
}

impl dwow_serial::Encodable for FundSwapParamsV1 { fn encode<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<usize> { let b = self.encode(); w.write_all(&b)?; Ok(b.len()) } }
impl dwow_serial::Decodable for FundSwapParamsV1 { fn decode<D: std::io::Read>(d: &mut D) -> std::io::Result<Self> { let mut b = vec![]; d.read_to_end(&mut b)?; Self::decode(&b).map_err(|e| std::io::Error::other(format!("{e}"))) } }
impl FundSwapParamsV1 {
    pub fn encode(&self) -> Vec<u8> {
        let cap = 66 + self.merkle_proof.len() * 32;
        let mut buf = Vec::with_capacity(cap);
        buf.extend_from_slice(&self.swap_id.to_repr()); buf.extend_from_slice(&self.value_commit.to_bytes());
        buf.push(self.merkle_proof.len() as u8);
        for p in &self.merkle_proof { buf.extend_from_slice(&p.to_repr()); }
        buf.extend_from_slice(&self.merkle_root.to_bytes()); buf
    }
    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() < 67 { return Err(ContractError::IoError("FundSwapParamsV1: too short".into())); }
        let swap_id = read_base(&data[0..32])?;
        let value_commit = Option::<pallas::Point>::from(pallas::Point::from_bytes(data[32..64].try_into().unwrap())).ok_or_else(|| ContractError::IoError("FundSwapParamsV1: invalid value_commit".into()))?;
        let proof_count = data[64] as usize;
        let mp_end = 65 + proof_count * 32;
        if data.len() < mp_end + 32 { return Err(ContractError::IoError("FundSwapParamsV1: merkle_proof truncated".into())); }
        let mut merkle_proof = Vec::with_capacity(proof_count);
        for i in 0..proof_count { merkle_proof.push(read_base(&data[65+i*32..65+(i+1)*32])?); }
        let merkle_root = MerkleNode::from_bytes(data[mp_end..mp_end+32].try_into().unwrap()).ok_or_else(|| ContractError::IoError("FundSwapParamsV1: invalid merkle_root".into()))?;
        Ok(FundSwapParamsV1 { swap_id, value_commit, merkle_proof, merkle_root })
    }
}

/// State update for `OtcSwap::FundSwapV1`
#[derive(Debug, Clone)]
pub struct FundSwapUpdateV1 {
    /// The funded swap ID
    pub swap_id: SwapId,
}

impl dwow_serial::Encodable for FundSwapUpdateV1 { fn encode<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<usize> { let b = self.encode(); w.write_all(&b)?; Ok(b.len()) } }
impl dwow_serial::Decodable for FundSwapUpdateV1 { fn decode<D: std::io::Read>(d: &mut D) -> std::io::Result<Self> { let mut b = vec![]; d.read_to_end(&mut b)?; Self::decode(&b).map_err(|e| std::io::Error::other(format!("{e}"))) } }
impl FundSwapUpdateV1 {
    pub const ENCODED_SIZE: usize = 32;

    pub fn encode(&self) -> Vec<u8> {
        self.swap_id.to_repr().to_vec()
    }

    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != Self::ENCODED_SIZE {
            return Err(ContractError::IoError(format!(
                "FundSwapUpdateV1: expected {} bytes, got {}",
                Self::ENCODED_SIZE,
                data.len()
            )));
        }
        let swap_id = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[0..32].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("FundSwapUpdateV1: invalid swap_id".into()))?;
        Ok(FundSwapUpdateV1 { swap_id })
    }
}

/// Parameters for `OtcSwap::ExecuteSwapV1`
#[derive(Debug, Clone,)]
pub struct ExecuteSwapParamsV1 {
    /// Swap ID
    pub swap_id: SwapId,
    /// Bob's secret (proves he's the counterparty)
    pub bob_secret: pallas::Base,
    /// Nullifier revealing the swap is executed
    pub spent_nullifier: pallas::Base,
    /// Alice's recipient pubkey (for Bob's coins to Alice)
    pub alice_recipient: PublicKey,
    /// Bob's recipient pubkey (for Alice's coins to Bob)
    pub bob_recipient: PublicKey,
}

impl dwow_serial::Encodable for ExecuteSwapParamsV1 { fn encode<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<usize> { let b = self.encode(); w.write_all(&b)?; Ok(b.len()) } }
impl dwow_serial::Decodable for ExecuteSwapParamsV1 { fn decode<D: std::io::Read>(d: &mut D) -> std::io::Result<Self> { let mut b = vec![]; d.read_to_end(&mut b)?; Self::decode(&b).map_err(|e| std::io::Error::other(format!("{e}"))) } }
impl ExecuteSwapParamsV1 { pub const ENCODED_SIZE: usize = 160; pub fn encode(&self) -> Vec<u8> { let mut buf = Vec::with_capacity(160); buf.extend_from_slice(&self.swap_id.to_repr()); buf.extend_from_slice(&self.bob_secret.to_repr()); buf.extend_from_slice(&self.spent_nullifier.to_repr()); buf.extend_from_slice(&self.alice_recipient.to_bytes()); buf.extend_from_slice(&self.bob_recipient.to_bytes()); buf } pub fn decode(data: &[u8]) -> Result<Self, ContractError> { if data.len() != 160 { return Err(ContractError::IoError(format!("ExecuteSwapParamsV1: expected 160 bytes, got {}", data.len()))); } Ok(ExecuteSwapParamsV1 { swap_id: read_base(&data[0..32])?, bob_secret: read_base(&data[32..64])?, spent_nullifier: read_base(&data[64..96])?, alice_recipient: PublicKey::from_bytes(data[96..128].try_into().unwrap()).map_err(|e| ContractError::IoError(format!("ExecuteSwapParamsV1: invalid alice_recipient: {}", e)))?, bob_recipient: PublicKey::from_bytes(data[128..160].try_into().unwrap()).map_err(|e| ContractError::IoError(format!("ExecuteSwapParamsV1: invalid bob_recipient: {}", e)))? }) } }

/// State update for `OtcSwap::ExecuteSwapV1`
#[derive(Debug, Clone)]
pub struct ExecuteSwapUpdateV1 {
    /// The executed swap ID
    pub swap_id: SwapId,
    /// Nullifier for the executed swap
    pub spent_nullifier: pallas::Base,
}

impl dwow_serial::Encodable for ExecuteSwapUpdateV1 { fn encode<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<usize> { let b = self.encode(); w.write_all(&b)?; Ok(b.len()) } }
impl dwow_serial::Decodable for ExecuteSwapUpdateV1 { fn decode<D: std::io::Read>(d: &mut D) -> std::io::Result<Self> { let mut b = vec![]; d.read_to_end(&mut b)?; Self::decode(&b).map_err(|e| std::io::Error::other(format!("{e}"))) } }
impl ExecuteSwapUpdateV1 {
    pub const ENCODED_SIZE: usize = 64;

    pub fn encode(&self) -> Vec<u8> {
        let mut b = Vec::with_capacity(Self::ENCODED_SIZE);
        b.extend_from_slice(&self.swap_id.to_repr());
        b.extend_from_slice(&self.spent_nullifier.to_repr());
        b
    }

    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != Self::ENCODED_SIZE {
            return Err(ContractError::IoError(format!(
                "ExecuteSwapUpdateV1: expected {} bytes, got {}",
                Self::ENCODED_SIZE,
                data.len()
            )));
        }
        let swap_id = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[0..32].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("ExecuteSwapUpdateV1: invalid swap_id".into()))?;
        let spent_nullifier = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[32..64].try_into().unwrap(),
        ))
        .ok_or_else(|| {
            ContractError::IoError("ExecuteSwapUpdateV1: invalid spent_nullifier".into())
        })?;
        Ok(ExecuteSwapUpdateV1 { swap_id, spent_nullifier })
    }
}

/// Parameters for `OtcSwap::CancelSwapV1`
#[derive(Debug, Clone,)]
pub struct CancelSwapParamsV1 {
    /// Swap ID
    pub swap_id: SwapId,
    /// Alice's secret (must match creator)
    pub alice_secret: pallas::Base,
    /// Nullifier revealing the swap is cancelled
    pub spent_nullifier: pallas::Base,
    /// Current block height (for timeout verification on Funded state)
    pub current_block: u64,
    /// Timeout block height
    pub timeout: u64,
    /// Recipient public key for refund
    pub recipient_pubkey: PublicKey,
}

impl dwow_serial::Encodable for CancelSwapParamsV1 { fn encode<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<usize> { let b = self.encode(); w.write_all(&b)?; Ok(b.len()) } }
impl dwow_serial::Decodable for CancelSwapParamsV1 { fn decode<D: std::io::Read>(d: &mut D) -> std::io::Result<Self> { let mut b = vec![]; d.read_to_end(&mut b)?; Self::decode(&b).map_err(|e| std::io::Error::other(format!("{e}"))) } }
impl CancelSwapParamsV1 { pub const ENCODED_SIZE: usize = 144; pub fn encode(&self) -> Vec<u8> { let mut buf = Vec::with_capacity(144); buf.extend_from_slice(&self.swap_id.to_repr()); buf.extend_from_slice(&self.alice_secret.to_repr()); buf.extend_from_slice(&self.spent_nullifier.to_repr()); buf.extend_from_slice(&self.current_block.to_le_bytes()); buf.extend_from_slice(&self.timeout.to_le_bytes()); buf.extend_from_slice(&self.recipient_pubkey.to_bytes()); buf } pub fn decode(data: &[u8]) -> Result<Self, ContractError> { if data.len() != 144 { return Err(ContractError::IoError(format!("CancelSwapParamsV1: expected 144 bytes, got {}", data.len()))); } Ok(CancelSwapParamsV1 { swap_id: read_base(&data[0..32])?, alice_secret: read_base(&data[32..64])?, spent_nullifier: read_base(&data[64..96])?, current_block: u64::from_le_bytes(data[96..104].try_into().unwrap()), timeout: u64::from_le_bytes(data[104..112].try_into().unwrap()), recipient_pubkey: PublicKey::from_bytes(data[112..144].try_into().unwrap()).map_err(|e| ContractError::IoError(format!("CancelSwapParamsV1: invalid recipient_pubkey: {}", e)))? }) }
}

/// State update for `OtcSwap::CancelSwapV1`
#[derive(Debug, Clone)]
pub struct CancelSwapUpdateV1 {
    /// The cancelled swap ID
    pub swap_id: SwapId,
    /// Nullifier for the cancelled swap
    pub spent_nullifier: pallas::Base,
}

impl dwow_serial::Encodable for CancelSwapUpdateV1 { fn encode<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<usize> { let b = self.encode(); w.write_all(&b)?; Ok(b.len()) } }
impl dwow_serial::Decodable for CancelSwapUpdateV1 { fn decode<D: std::io::Read>(d: &mut D) -> std::io::Result<Self> { let mut b = vec![]; d.read_to_end(&mut b)?; Self::decode(&b).map_err(|e| std::io::Error::other(format!("{e}"))) } }
impl CancelSwapUpdateV1 {
    pub const ENCODED_SIZE: usize = 64;

    pub fn encode(&self) -> Vec<u8> {
        let mut b = Vec::with_capacity(Self::ENCODED_SIZE);
        b.extend_from_slice(&self.swap_id.to_repr());
        b.extend_from_slice(&self.spent_nullifier.to_repr());
        b
    }

    pub fn decode(data: &[u8]) -> Result<Self, ContractError> {
        if data.len() != Self::ENCODED_SIZE {
            return Err(ContractError::IoError(format!(
                "CancelSwapUpdateV1: expected {} bytes, got {}",
                Self::ENCODED_SIZE,
                data.len()
            )));
        }
        let swap_id = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[0..32].try_into().unwrap(),
        ))
        .ok_or_else(|| ContractError::IoError("CancelSwapUpdateV1: invalid swap_id".into()))?;
        let spent_nullifier = Option::<pallas::Base>::from(pallas::Base::from_repr(
            data[32..64].try_into().unwrap(),
        ))
        .ok_or_else(|| {
            ContractError::IoError("CancelSwapUpdateV1: invalid spent_nullifier".into())
        })?;
        Ok(CancelSwapUpdateV1 { swap_id, spent_nullifier })
    }
}
